services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Contao frontend module Markocupic\ContaoSchuleEttiswilLicensesBundle\Controller\FrontendModule\SchuleEttiswilLicensesListModuleController
    Markocupic\ContaoSchuleEttiswilLicensesBundle\Controller\FrontendModule\SchuleEttiswilLicensesListModuleController:
        arguments:
            - '@twig'
        tags:
            - { name: contao.frontend_module, category: schule_ettiswil, template: mod_schule_ettiswil_licenses_list_module, type: schule_ettiswil_licenses_list_module }
            - { name: container.service_subscriber }
        public: true

    # Export service
    Markocupic\ContaoSchuleEttiswilLicensesBundle\ExportData\Excel: ~
