services:

    # Contao frontend module Markocupic\ContaoIsotopeSchulfilmeBundle\Controller\FrontendModule\ProductListFilterDisplayModuleController
    Markocupic\ContaoIsotopeSchulfilmeBundle\Controller\FrontendModule\ProductListFilterDisplayModuleController:
        arguments:
            - '@session'
        tags:
            - { name: contao.frontend_module, category: schulfilme_isotope, template: mod_product_list_filter_display_module, type: product_list_filter_display_module }
            - { name: container.service_subscriber }
        public: true

    # Contao content element Markocupic\ContaoIsotopeSchulfilmeBundle\Controller\ContentElement\HerooImageElementController
    Markocupic\ContaoIsotopeSchulfilmeBundle\Controller\ContentElement\HerooImageElementController:
        tags:
            - { name: contao.content_element, category: image_elementsss, template: ce_heroo_image_element, type: heroo_image_element }
            - { name: container.service_subscriber }
        public: true

    # Custom route
    Markocupic\ContaoIsotopeSchulfilmeBundle\Controller\MyCustomController:
        arguments:
            - '@twig'
        public: true
