services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $bagName: '%resource_booking_bundle.session.attribute_bag_name%'

    _instanceof:
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [ setContainer, [ '@service_container' ] ]

    Markocupic\ResourceBookingBundle\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model,Config,Event}

    # Subscribers: Handle ajay requests
    Markocupic\ResourceBookingBundle\EventSubscriber\AjaxRequestEventSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    Markocupic\ResourceBookingBundle\AjaxController\BookingController:
        tags:
            - { name: markocupic.resource_booking.ajax_controller, alias: booking }

    Markocupic\ResourceBookingBundle\AjaxController\CancelController:
        tags:
            - { name: markocupic.resource_booking.ajax_controller, alias: cancelBooking }

    Markocupic\ResourceBookingBundle\AjaxController\ApplyFilterController:
        tags:
            - { name: markocupic.resource_booking.ajax_controller, alias: applyFilter }

    Markocupic\ResourceBookingBundle\AjaxController\JumpWeekController:
        tags:
            - { name: markocupic.resource_booking.ajax_controller, alias: jumpWeek }

    Markocupic\ResourceBookingBundle\AjaxController\BookingFormValidationController:
        tags:
            - { name: markocupic.resource_booking.ajax_controller, alias: bookingFormValidation }

    # Contao frontend module "resourceBookingWeekcalendar"
    Markocupic\ResourceBookingBundle\Controller\FrontendModule\ResourceBookingWeekcalendarController:
        tags:
            - { name: contao.frontend_module, category: resourceBooking, type: resourceBookingWeekcalendar }

    # Register session bag
    Markocupic\ResourceBookingBundle\Session\Attribute\ArrayAttributeBag:
        calls:
            - [ 'setName', [ '%resource_booking_bundle.session.attribute_bag_name%' ] ]

    # Contao hook: addCustomRegexp
    Markocupic\ResourceBookingBundle\EventListener\ContaoHooks\Regexp:
        tags:
            - { name: contao.hook, hook: addCustomRegexp, method: onCustomRegexp, priority: 0 }

        # Migration class: Add booking uuid
    Markocupic\ResourceBookingBundle\Migration\AddBookingUuid\AddBookingUuid:
        tags:
            - { name: contao.migration, priority: 0 }
