# services.yml
services:

  # Ajax helper
  Markocupic\ResourceBookingBundle\Booking\BookingTable:
    arguments:
    - '@contao.framework'
    - '@security.helper'
    - '@session'
    - '@request_stack'
    - '@Markocupic\ResourceBookingBundle\User\LoggedInFrontendUser'
    - '%resource_booking_bundle.session.attribute_bag_name%'
    public: true

  # Json response for ajax calls
  Markocupic\ResourceBookingBundle\Response\AjaxResponse:
    public: true

  # Initialize application
  Markocupic\ResourceBookingBundle\AppInitialization\Initialize:
    arguments:
    - '@contao.framework'
    - '@session'
    - '@request_stack'
    - '%resource_booking_bundle.session.attribute_bag_name%'

  # Contao frontend module "resourceBookingWeekcalendar"
  Markocupic\ResourceBookingBundle\Controller\FrontendModule\ResourceBookingWeekcalendarController:
    arguments:
    - '@contao.framework'
    - '@request_stack'
    - '@event_dispatcher'
    - '@Markocupic\ResourceBookingBundle\AppInitialization\Initialize'
    - '@Markocupic\ResourceBookingBundle\Response\AjaxResponse'
    calls:
    - ['setContainer', ['@Psr\Container\ContainerInterface']]
    tags:
    - { name: contao.frontend_module, category: resourceBooking, type: resourceBookingWeekcalendar }
    public: true

  # Cron: Delete daily no more used bookings
  Markocupic\ResourceBookingBundle\Cron\Cron:
    arguments:
    - '@contao.framework'
    public: true

  # Register session bag
  Markocupic\ResourceBookingBundle\Session\Attribute\ArrayAttributeBag:
    class: Markocupic\ResourceBookingBundle\Session\Attribute\ArrayAttributeBag
    arguments:
    - '@contao.framework'
    - '@request_stack'
    - '@session'
    - '@security.helper'
    - '%resource_booking_bundle.session.attribute_bag_key%'
    calls:
    - ['setName', ['%resource_booking_bundle.session.attribute_bag_name%']]

  # Booking: Booking helper class
  Markocupic\ResourceBookingBundle\Booking\Booking:
    arguments:
    - '@contao.framework'
    - '@session'
    - '@request_stack'
    - '@Markocupic\ResourceBookingBundle\User\LoggedInFrontendUser'
    - '%resource_booking_bundle.session.attribute_bag_name%'
    public: true

  # LoggedInFrontendUser: User class
  Markocupic\ResourceBookingBundle\User\LoggedInFrontendUser:
    arguments:
    - '@security.helper'
    public: true