services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $bagName: '%markocupic_resource_booking.session.attribute_bag_name%'

    _instanceof:
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [ setContainer, [ '@service_container' ] ]

    Markocupic\ResourceBookingBundle\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model,Config,Event}

    # Subscribers: Add backend assets
    Markocupic\ResourceBookingBundle\EventSubscriber\KernelRequestSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # Subscribers: Handle ajay requests
    Markocupic\ResourceBookingBundle\EventSubscriber\AjaxRequestEventSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # Ajax controller
    Markocupic\ResourceBookingBundle\AjaxController\BookingController:
        tags:
            - { name: markocupic_resource_booking.ajax_controller, alias: booking }


    # Ajax controller
    Markocupic\ResourceBookingBundle\AjaxController\CancelController:
        tags:
            - { name: markocupic_resource_booking.ajax_controller, alias: cancelBooking }

    # Ajax controller
    Markocupic\ResourceBookingBundle\AjaxController\ApplyFilterController:
        tags:
            - { name: markocupic_resource_booking.ajax_controller, alias: applyFilter }

    # Ajax controller
    Markocupic\ResourceBookingBundle\AjaxController\BookingFormValidationController:
        tags:
            - { name: markocupic_resource_booking.ajax_controller, alias: bookingFormValidation }

    # Ajax controller
    Markocupic\ResourceBookingBundle\AjaxController\RefreshDataController:
        tags:
            - { name: markocupic_resource_booking.ajax_controller, alias: refreshData }

    # Register session bag
    Markocupic\ResourceBookingBundle\Session\Attribute\ArrayAttributeBag:
        calls:
            - [ 'setName', [ '%markocupic_resource_booking.session.attribute_bag_name%' ] ]

    # Contao hook: addCustomRegexp
    Markocupic\ResourceBookingBundle\EventListener\ContaoHooks\Regexp:
        tags:
            - { name: contao.hook, hook: addCustomRegexp, method: onCustomRegexp, priority: 0 }

        # Migration class: Add booking uuid
    Markocupic\ResourceBookingBundle\Migration\AddBookingUuid\AddBookingUuid:
        tags:
            - { name: contao.migration, priority: 0 }
