services:
  _defaults:
    autowire: true
    public: true
    autoconfigure: true

  # Autogenerate users and members from office365 database
  Markocupic\Office365Bundle\EventListener\ContaoHooks\PostLoginListener: ~

  # Enable login with email address
  Markocupic\Office365Bundle\EventListener\ContaoHooks\ImportUserListener: ~


