services:

  Markocupic\ImportFromCsvBundle\Import\ImportFromCsv:
    arguments:
      - '@contao.framework'
      - '@database_connection'
      - '@translator'
      - '@session'
      - '@security.encoder_factory'
      - '@Markocupic\ImportFromCsvBundle\Import\Field\FieldFactory'
      - '%kernel.project_dir%'
    public: true

  Markocupic\ImportFromCsvBundle\Import\ImportFromCsvHelper:
    arguments:
      - '@contao.framework'
      - '@Markocupic\ImportFromCsvBundle\Import\ImportFromCsv'
      - '%kernel.project_dir%'
    public: true

  Markocupic\ImportFromCsvBundle\Import\Field\FieldFactory:
    arguments:
      - '@Markocupic\ImportFromCsvBundle\Import\Field\Field'
    public: true

  Markocupic\ImportFromCsvBundle\Import\Field\Field:
    public: true

  Markocupic\ImportFromCsvBundle\Cron\Cron:
    arguments:
      - '@contao.framework'
      - '@Markocupic\ImportFromCsvBundle\Import\ImportFromCsvHelper'
      - '@monolog.logger.contao'
    public: true

  Markocupic\ImportFromCsvBundle\Dca\TlImportFromCsv:
    arguments:
      - '@contao.framework'
      - '@request_stack'
      - '@session'
      - '@translator'
      - '@twig'
      - '@Markocupic\ImportFromCsvBundle\Import\ImportFromCsvHelper'
      - '%kernel.project_dir%'
    public: true